databases:
  - name: fooddemoapp
    plan: free
    databaseName: fooddemoapp
    user: fooddemoapp

services:
  - type: web
    name: fooddemoapp
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fooddemoapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
